// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	handler25 "mvtable/internal/app/collaboration/handler"
	service8 "mvtable/internal/app/collaboration/service"
	handler3 "mvtable/internal/app/file/handler"
	service3 "mvtable/internal/app/file/service"
	handler2 "mvtable/internal/app/invite_code/handler"
	service2 "mvtable/internal/app/invite_code/service"
	handler23 "mvtable/internal/app/mv_dashboard/handler"
	service23 "mvtable/internal/app/mv_dashboard/service"
	handler22 "mvtable/internal/app/mv_dashboard_chart/handler"
	service22 "mvtable/internal/app/mv_dashboard_chart/service"
	handler18 "mvtable/internal/app/mv_doc/handler"
	service18 "mvtable/internal/app/mv_doc/service"
	handler8 "mvtable/internal/app/mv_field/handler"
	service7 "mvtable/internal/app/mv_field/service"
	handler9 "mvtable/internal/app/mv_folder/handler"
	service9 "mvtable/internal/app/mv_folder/service"
	handler19 "mvtable/internal/app/mv_form_submit/handler"
	service19 "mvtable/internal/app/mv_form_submit/service"
	handler6 "mvtable/internal/app/mv_project/handler"
	service5 "mvtable/internal/app/mv_project/service"
	handler13 "mvtable/internal/app/mv_project_advanced_perm/handler"
	service13 "mvtable/internal/app/mv_project_advanced_perm/service"
	handler12 "mvtable/internal/app/mv_project_perm/handler"
	service12 "mvtable/internal/app/mv_project_perm/service"
	handler11 "mvtable/internal/app/mv_project_state/handler"
	service11 "mvtable/internal/app/mv_project_state/service"
	handler10 "mvtable/internal/app/mv_record/handler"
	service10 "mvtable/internal/app/mv_record/service"
	handler24 "mvtable/internal/app/mv_rich_text_content/handler"
	service24 "mvtable/internal/app/mv_rich_text_content/service"
	handler7 "mvtable/internal/app/mv_table_schema/handler"
	service6 "mvtable/internal/app/mv_table_schema/service"
	handler21 "mvtable/internal/app/mv_template_project/handler"
	service21 "mvtable/internal/app/mv_template_project/service"
	handler20 "mvtable/internal/app/mv_template_tag/handler"
	service20 "mvtable/internal/app/mv_template_tag/service"
	handler14 "mvtable/internal/app/mv_view/handler"
	service14 "mvtable/internal/app/mv_view/service"
	handler17 "mvtable/internal/app/mv_view_board/handler"
	service17 "mvtable/internal/app/mv_view_board/service"
	handler15 "mvtable/internal/app/mv_view_form/handler"
	service15 "mvtable/internal/app/mv_view_form/service"
	handler16 "mvtable/internal/app/mv_view_table/handler"
	service16 "mvtable/internal/app/mv_view_table/service"
	handler5 "mvtable/internal/app/team/handler"
	service4 "mvtable/internal/app/team/service"
	"mvtable/internal/app/user/handler"
	"mvtable/internal/app/user/service"
	handler4 "mvtable/internal/app/website_config/handler"
	handler26 "mvtable/internal/app/website_visit/handler"
	service25 "mvtable/internal/app/website_visit/service"
	"mvtable/internal/pkg/config"
	"mvtable/internal/server"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	userService := service.NewUserService()
	userHandler := handler.NewUserHandler(userService)
	inviteCodeService := service2.NewInviteCodeService()
	inviteCodeHandler := handler2.NewInviteCodeHandler(inviteCodeService)
	fileService := service3.NewFileService()
	fileHandler := handler3.NewFileHandler(fileService)
	websiteConfigHandler := handler4.NewWebsiteConfigHandler()
	teamService := service4.NewTeamService()
	teamHandler := handler5.NewTeamHandler(teamService)
	mvProjectService := service5.NewMvProjectService()
	mvProjectHandler := handler6.NewMvProjectHandler(mvProjectService)
	mvTableSchemaService := service6.NewMvTableSchemaService()
	mvTableSchemaHandler := handler7.NewMvTableSchemaHandler(mvTableSchemaService)
	mvFieldService := service7.NewMvFieldService()
	hub := service8.NewHub()
	mvFieldHandler := handler8.NewMvFieldHandler(mvFieldService, hub)
	mvFolderService := service9.NewMvFolderService()
	mvFolderHandler := handler9.NewMvFolderHandler(mvFolderService)
	mvRecordService := service10.NewMvRecordService()
	mvRecordHandler := handler10.NewMvRecordHandler(mvRecordService)
	mvProjectStateService := service11.NewMvProjectStateService()
	mvProjectStateHandler := handler11.NewMvProjectStateHandler(mvProjectStateService)
	mvProjectPermissionService := service12.NewMvProjectPermissionService()
	mvProjectPermissionHandler := handler12.NewMvProjectPermissionHandler(mvProjectPermissionService)
	mvProjectAdvancedPermService := service13.NewMvProjectAdvancedPermService()
	mvProjectAdvancedPermHandler := handler13.NewMvProjectAdvancedPermHandler(mvProjectAdvancedPermService)
	mvViewFormService := service14.NewMvViewFormService()
	mvViewHandler := handler14.NewMvViewHandler(mvViewFormService)
	serviceMvViewFormService := service15.NewMvViewFormService()
	mvViewFormHandler := handler15.NewMvViewFormHandler(serviceMvViewFormService)
	mvViewTableService := service16.NewMvViewTableService()
	mvViewTableHandler := handler16.NewMvViewTableHandler(mvViewTableService)
	mvViewBoardService := service17.NewMvViewBoardService()
	mvViewBoardHandler := handler17.NewMvViewBoardHandler(mvViewBoardService)
	mvDocService := service18.NewMvDocService()
	mvDocHandler := handler18.NewMvDocHandler(mvDocService)
	mvFormSubmitService := service19.NewMvFormSubmitService()
	mvFormSubmitHandler := handler19.NewMvFormSubmitHandler(mvFormSubmitService)
	mvTemplateTagService := service20.NewMvTemplateTagService()
	mvTemplateTagHandler := handler20.NewMvTemplateTagHandler(mvTemplateTagService)
	mvTemplateProjectService := service21.NewMvTemplateProjectService()
	mvTemplateProjectHandler := handler21.NewMvTemplateProjectHandler(mvTemplateProjectService)
	mvDashboardChartService := service22.NewMvDashboardChartService()
	mvDashboardChartHandler := handler22.NewMvDashboardChartHandler(mvDashboardChartService)
	mvDashboardService := service23.NewMvDashboardService()
	mvDashboardHandler := handler23.NewMvDashboardHandler(mvDashboardService)
	mvRichTextContentService := service24.NewMvRichTextContentService()
	mvRichTextContentHandler := handler24.NewMvRichTextContentHandler(mvRichTextContentService)
	lockManager := service8.NewLockManager()
	collaborationService := service8.NewCollaborationService(lockManager, mvRecordService, mvFieldService, userService, hub)
	collaborationHandler := handler25.NewCollaborationHandler(hub, collaborationService)
	websiteVisitService := service25.NewWebsiteVisitService()
	websiteVisitHandler := handler26.NewWebsiteVisitHandler(websiteVisitService)
	router := server.NewRouter(userHandler, inviteCodeHandler, fileHandler, websiteConfigHandler, teamHandler, mvProjectHandler, mvTableSchemaHandler, mvFieldHandler, mvFolderHandler, mvRecordHandler, mvProjectStateHandler, mvProjectPermissionHandler, mvProjectAdvancedPermHandler, mvViewHandler, mvViewFormHandler, mvViewTableHandler, mvViewBoardHandler, mvDocHandler, mvFormSubmitHandler, mvTemplateTagHandler, mvTemplateProjectHandler, mvDashboardChartHandler, mvDashboardHandler, mvRichTextContentHandler, collaborationHandler, websiteVisitHandler)
	httpServer := server.NewHTTPServer(cfg, router)
	app := &App{
		HTTPServer: httpServer,
	}
	return app, func() {
	}, nil
}

// wire.go:

// App 应用结构
type App struct {
	HTTPServer *server.HTTPServer
}
